import { open as fsOpen, stat as fsStat, unlink as fsUnlink } from 'node:fs/promises';
import { join, resolve as pathResolve } from 'node:path';

import {
  defaultTemplate,
  csharpTemplate,
  typescriptTemplate,
  javascriptTemplate,
  pythonTemplate,
  javaTemplate,
  goTemplate,
  rustTemplate,
  rubyTemplate,
  sqlTemplate,
  hclTemplate,
  shellTemplate,
  powershellTemplate,
} from './gitignoreTemplates.generated';

// Thin injectable seam for write-path fs operations. Tests may replace these
// methods to exercise failure paths without real fs races or timing dependencies.
// Production code uses the real node:fs/promises implementations below.
export const _fsOps = {
  open: fsOpen,
  stat: fsStat,
  unlink: fsUnlink,
};

// Canonical key type for all supported language templates.
export type GitignoreTemplateKey =
  | 'csharp'
  | 'typescript'
  | 'javascript'
  | 'python'
  | 'java'
  | 'go'
  | 'rust'
  | 'ruby'
  | 'sql'
  | 'hcl'
  | 'shell'
  | 'powershell';

// Stable render order for language sections.
const CANONICAL_ORDER: readonly GitignoreTemplateKey[] = [
  'csharp',
  'typescript',
  'javascript',
  'python',
  'java',
  'go',
  'rust',
  'ruby',
  'sql',
  'hcl',
  'shell',
  'powershell',
];

const TEMPLATE_MAP: Record<GitignoreTemplateKey, string> = {
  csharp: csharpTemplate,
  typescript: typescriptTemplate,
  javascript: javascriptTemplate,
  python: pythonTemplate,
  java: javaTemplate,
  go: goTemplate,
  rust: rustTemplate,
  ruby: rubyTemplate,
  sql: sqlTemplate,
  hcl: hclTemplate,
  shell: shellTemplate,
  powershell: powershellTemplate,
};

// Languages that map to default only — no dedicated template section.
const DEFAULT_ONLY_VALUES = new Set([
  'markdown',
  'blank',
  'swift',
  'yaml',
  'json',
  'unknown',
  'custom',
]);

// Normalize a raw language string to a canonical key or undefined (default only).
export function normalizeGitignoreLanguage(value: string): GitignoreTemplateKey | undefined {
  const v = value.trim().toLowerCase();
  switch (v) {
    case 'csharp':
    case 'c#':
    case 'dotnet':
    case '.net':
      return 'csharp';
    case 'typescript':
    case 'ts':
    case 'tsx':
      return 'typescript';
    case 'javascript':
    case 'js':
    case 'jsx':
    case 'node':
      return 'javascript';
    case 'python':
    case 'py':
      return 'python';
    case 'java':
    case 'jvm':
      return 'java';
    case 'go':
    case 'golang':
      return 'go';
    case 'rust':
    case 'rs':
      return 'rust';
    case 'ruby':
    case 'rb':
    case 'rails':
      return 'ruby';
    case 'sql':
    case 'database':
      return 'sql';
    case 'hcl':
    case 'terraform':
    case 'opentofu':
    case 'tf':
      return 'hcl';
    case 'shell':
    case 'bash':
    case 'sh':
    case 'zsh':
      return 'shell';
    case 'powershell':
    case 'pwsh':
    case 'ps1':
      return 'powershell';
    default:
      return DEFAULT_ONLY_VALUES.has(v) ? undefined : undefined;
  }
}

// Resolve a list of raw language strings to unique template keys in canonical order.
export function resolveGitignoreTemplateKeys(languages: string[]): GitignoreTemplateKey[] {
  const seen = new Set<GitignoreTemplateKey>();
  for (const lang of languages) {
    const key = normalizeGitignoreLanguage(lang);
    if (key !== undefined) seen.add(key);
  }
  return CANONICAL_ORDER.filter((k) => seen.has(k));
}

const GENERATED_HEADER =
  '# Generated by TaskSail — edit freely, this file will not be overwritten.\n';

// Render a complete .gitignore from raw language strings.
// Output: generated header + default section + language sections in canonical order.
// Uses LF line endings and ends with exactly one trailing newline.
export function renderGitignore(languages: string[]): string {
  const keys = resolveGitignoreTemplateKeys(languages);
  const parts: string[] = [GENERATED_HEADER, defaultTemplate];
  for (const key of keys) {
    parts.push(TEMPLATE_MAP[key]);
  }
  // Join all parts (each template already starts/ends with \n), normalize to LF,
  // then ensure exactly one trailing newline.
  const joined = parts.join('').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  return joined.replace(/\n+$/, '\n');
}

// Create-only writer. Returns 'created' if .gitignore was written, 'exists' if it
// already existed. Uses flag 'wx' so the open fails atomically with EEXIST if the
// file already exists — never overwrites an existing .gitignore.
export async function writeGitignoreIfMissing(
  repoDir: string,
  languages: string[],
): Promise<'created' | 'exists'> {
  const gitignorePath = join(pathResolve(repoDir), '.gitignore');
  const content = renderGitignore(languages);
  const encoded = Buffer.from(content, 'utf8');

  let handle: Awaited<ReturnType<typeof fsOpen>> | undefined;
  try {
    handle = await _fsOps.open(gitignorePath, 'wx');
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
      return 'exists';
    }
    throw err;
  }

  // Exclusive open succeeded — this process owns the file. Write, then close.
  // A close() failure after a successful write is itself a failure: buffered or
  // delayed-allocation filesystems can surface ENOSPC/EIO only at close, so the
  // bytes may not be durably persisted. 'created' is returned only when BOTH the
  // write and the close succeed.
  let failure: unknown;
  try {
    await handle.writeFile(encoded);
  } catch (err) {
    failure = err;
  }

  // Capture the created file's identity (inode/device) from the still-open handle
  // BEFORE closing it — a closed handle throws EBADF on stat — so a later cleanup
  // can prove the path still refers to the file we created, whether the write or
  // the close is the operation that fails.
  let createdIdentity: { ino: number; dev: number } | undefined;
  try {
    const s = await handle.stat();
    createdIdentity = { ino: s.ino, dev: s.dev };
  } catch {
    // Identity unknown — cleanup will be skipped rather than risk deleting another file.
  }

  try {
    await handle.close();
  } catch (closeErr) {
    if (failure === undefined) failure = closeErr;
  }

  if (failure !== undefined) {
    // Bounded best-effort cleanup: only unlink if the path still resolves to the
    // same file identity captured from the exclusive-open handle. If identity is
    // unknown or no longer matches, skip cleanup — never remove someone else's file.
    if (createdIdentity !== undefined) {
      try {
        const pathStat = await _fsOps.stat(gitignorePath);
        if (pathStat.ino === createdIdentity.ino && pathStat.dev === createdIdentity.dev) {
          await _fsOps.unlink(gitignorePath);
        }
      } catch {
        // Skip cleanup if the path stat fails.
      }
    }
    throw failure;
  }

  return 'created';
}
