export const deepFocusStrings = {
  popover: {
    globalHeader: 'For all primary targets',
    primaryHeader: (name: string) => `For ${name}`,
    repoRootHeader: 'For repo root',
    gestureHint: 'Hold a row to use it here.',
    actions: {
      makePrimary: 'Add Primary Target',
      setGlobalTest: 'Use as test for all',
      addGlobalSupport: 'Add as support for all',
      removeGlobal: 'Remove from all primary targets',
      setPrimaryTest: (name: string) => `Use as test for ${name}`,
      addPrimarySupport: (name: string) => `Add as support for ${name}`,
      removePrimaryMember: (name: string) => `Remove from ${name}`,
      removePrimary: 'Remove Primary Target',
    },
  },
  cards: {
    globalHeader: 'Global',
    repoRootHeader: 'Whole repo',
  },
  emptySlots: {
    globalTest: 'No test folder selected for all primary targets.',
    globalSupport: 'No support folders selected for all primary targets.',
    primaryTest: (name: string) => `No test folder selected for ${name}.`,
    primarySupport: (name: string) => `No support folders selected for ${name}.`,
  },
  repoRootNotice: 'This primary target covers the whole tree. No extra tests or supports needed.',
  cursor: {
    globalVisible: 'Viewing all primaries',
    globalAnnouncement: 'Now editing all primaries.',
    primaryVisible: (name: string) => `Viewing ${name}`,
    primaryAnnouncement: (name: string) => `Now editing ${name}.`,
    repoRootVisible: 'Viewing repo root',
    repoRootAnnouncement: 'Now editing repo root.',
  },
  validation: {
    'scoped-test-equals-self': "A primary can't also be its own test.",
    'scoped-test-equals-other-primary': 'Another primary target owns this folder. Choose a different test.',
    'scoped-test-ancestor-of-primary': "This test contains the primary. Choose a folder that's separate.",
    'scoped-support-equals-self': "A primary can't also be its own support.",
    'scoped-support-equals-primary-test': 'This is already the test. Pick one role.',
    'scoped-support-equals-other-primary': 'Another primary target owns this folder.',
    'scoped-support-inside-own-primary-writable': 'This is already covered by the primary as writable. Pick a folder outside it.',
    'scoped-support-redundant-under-test': 'This support is already covered by the primary test target.',
    'scoped-support-redundant-under-support': 'This support is already covered by another support entry.',
    'primary-target-inside-primary-writable': 'This is already covered by a parent primary target.',
    'global-support-inside-primary-writable': 'This support is already covered by a primary target.',
    'global-support-redundant-under-global-test': 'This support is already covered by the global test target.',
    'global-support-redundant-under-global-support': 'This support is already covered by another global support entry.',
    'cross-primary-support-overlaps-writable': "This support is already part of another primary target's writable area.",
    'support-duplicated-across-scopes': 'This support is also listed on a specific primary. Pick one scope.',
    'scoped-fields-on-repo-root-primary': 'A repo-root primary covers the whole tree. Test and support folders apply automatically.',
  },
  footerIssues: (count: number) => `${count} ${count === 1 ? 'issue' : 'issues'}`,
  toast: {
    primaryRemoved: (name: string) => `${name} removed`,
    testRemoved: (name: string) => `${name} removed as test`,
    supportRemoved: (name: string) => `${name} removed as support`,
    stacked: (label: string, count: number) => `${label} · ${count} recent`,
    undo: 'Undo',
    undoStacked: (count: number) => `Undo (${count})`,
  },
} as const;
