"""Canonical markdown section-name constants."""
from __future__ import annotations

from .markdown_contract import load_markdown_contract

_SECTION_NAMES = load_markdown_contract().section_names

TASK_LINEAGE = _SECTION_NAMES["TASK_LINEAGE"]
TASK_METADATA = _SECTION_NAMES["TASK_METADATA"]
CONTEXT_PACK_BINDING = _SECTION_NAMES["CONTEXT_PACK_BINDING"]
REVIEW_OUTCOME = _SECTION_NAMES["REVIEW_OUTCOME"]
DECISION = _SECTION_NAMES["DECISION"]
DIFFICULTY_LEVEL = _SECTION_NAMES["DIFFICULTY_LEVEL"]
RECOMMENDED_EXECUTION = _SECTION_NAMES["RECOMMENDED_EXECUTION"]
CLOSEOUT_OWNER_AGENT_ID = _SECTION_NAMES["CLOSEOUT_OWNER_AGENT_ID"]
RETROSPECTIVE_REQUIRED = _SECTION_NAMES["RETROSPECTIVE_REQUIRED"]
