import { cleanup } from '@testing-library/react';
import { afterEach, beforeEach, vi } from 'vitest';

export function installAppTestHarness(): void {
  afterEach(() => {
    cleanup();
  });

  beforeEach(() => {
    Object.defineProperty(window, 'innerWidth', {
      configurable: true,
      writable: true,
      value: 1280,
    });

    window.desktopShell = {
      getBootstrapInfo: vi.fn(),
      onStreamEvent: vi.fn().mockReturnValue(vi.fn()),
      onPlannerEvent: vi.fn().mockReturnValue(vi.fn()),
      onTaskBoardUpdate: vi.fn().mockReturnValue(vi.fn()),
      getQueueStatus: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'queue.readStatus',
          mode: 'observed',
          queueDepth: 2,
          pendingReviewCount: 1,
          activeTaskId: 'CAP-CUSTOM-TERMINAL-04',
          operatorStatus: 'RUNNING',
          message: 'Observed repo queue state: 2 queued, 1 active. Current lifecycle: active.',
        },
      }),
      deletePendingItem: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'queue.deletePendingItem',
          mode: 'deleted',
          message: 'Removed pending queue item task-002.md.',
          queueName: 'task-002.md',
        },
      }),
      getEnvironmentStatus: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'environment.readStatus',
          mode: 'read-only',
          message: 'Desktop packaging and startup guidance remain read-only and host-native against the repo root.',
          platform: 'linux',
          repoRoot: '/repo/root',
          packageOutputDir: 'src/frontend/desktop/release/linux-unpacked',
          packageArtifactName: 'TaskSail.AppImage',
          packageCommand: 'npm run package:linux',
          hostMode: 'repo-root-native',
          validationSummary:
            'Native packaging guidance is available for the current host platform (linux). Repo root, workflow queue directories, and required helper seams are available for host-native desktop operation.',
          launchPolicy:
            'Launch the desktop shell host-native against the repo root. Repo workflow artifacts remain authoritative and are never relocated into the packaged app bundle.',
          helperStatuses: [
            {
              label: 'Dropbox task helper',
              path: 'src/backend/platform/queue/createDropboxTask.ts',
              available: true,
              detail: 'Platform TypeScript module for standard planner submission through AgentWorkSpace/dropbox/.',
            },
            {
              label: 'Follow-up task helper',
              path: 'src/backend/platform/queue/createFollowupTask.ts',
              available: true,
              detail: 'Platform TypeScript module for completed-task child-task follow-up creation.',
            },
            {
              label: 'Context-pack activation helper',
              path: 'src/backend/platform/context-pack/switch.ts',
              available: true,
              detail: 'Platform TypeScript module for the default operator startup activation flow.',
            },
          ],
          contextPackCommand: 'tsx src/backend/platform/context-pack/cli.ts --pack platform-default --mode status-only',
          contextPackWritePlanHint:
            'If activation needs a materialized plan, reuse the stable helper seam with `--write-plan` instead of reimplementing overlay logic in the desktop shell.',
          bootstrapFlowHint:
            'Structured bootstrap continues through `--bootstrap-repo-root` and `--bootstrap-answers-file` on the activation helper rather than desktop-specific setup commands.',
        },
      }),
      getObservabilitySnapshot: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'observability.readSnapshot',
          mode: 'read-only',
          message:
            'Repo observability reflects queue and artifact truth only. The desktop shell does not author workflow-policy artifacts.',
          queueDepth: 2,
          pendingReviewCount: 1,
          activeTaskId: 'CAP-CUSTOM-TERMINAL-04',
          activeTaskTitle: 'Observe queue artifacts',
          currentState: 'active',
          operatorStatus: 'RUNNING',
          pendingQueueItems: [],
          lifecycle: [
            { state: 'queued', observed: true, detail: '2 markdown task(s) currently waiting in AgentWorkSpace/dropbox/.' },
            { state: 'active', observed: true, detail: 'Active workflow context is visible in AgentWorkSpace/pendingitems/ or AgentWorkSpace/handoffs metadata for CAP-CUSTOM-TERMINAL-04.' },
          ],
          artifactReferences: [
            {
              label: 'Professional task handoff',
              path: 'AgentWorkSpace/handoffs/professional-task.md',
              kind: 'file',
              status: 'present',
              detail: 'Observe queue artifacts',
            },
            {
              label: 'Retrospective handoff',
              path: 'AgentWorkSpace/handoffs/retrospective-input.md',
              kind: 'file',
              status: 'present',
              detail: 'Observe queue artifacts',
            },
            {
              label: 'Implementation steps',
              path: 'AgentWorkSpace/ImplementationSteps',
              kind: 'directory',
              status: 'present',
              detail: '1 markdown artifact(s) available.',
            },
          ],
          policyBoundary:
            'Repo artifacts remain authoritative; desktop UI is observational only and never writes handoffs, pendingitems, or summaries directly.',
        },
      }),
      pickContextPackDirectory: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.pickDirectory',
          mode: 'selected',
          message: 'Selected.',
          purpose: 'discovery-root',
          selectedPath: '/tmp/estate-root',
        },
      }),
      discoverContextPackPrefill: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.discoverPrefill',
          mode: 'discovered',
          message: 'Discovered.',
          rootPath: '/tmp/estate-root',
          discoveryMode: 'distributed',
          estateType: 'distributed',
          suggestedContextPackId: 'orders-estate',
          suggestedDisplayName: 'Orders Estate',
          warnings: [],
          candidateRepos: [],
          candidateFocusAreas: [],
          highSignalPaths: [],
        },
      }),
      createContextPack: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.create',
          mode: 'created',
          message: 'Created.',
          commandPath: 'src/backend/scripts/python/bootstrap-context-pack.py',
          result: {
            contextPackId: 'orders-estate',
            displayName: 'Orders Estate',
            contextPackDir: '/tmp/context-packs/orders-estate',
            discoveryRoot: '/tmp/estate-root',
            discoveryMode: 'distributed',
            estateType: 'distributed-platform',
            defaultScopeMode: 'focused',
            bootstrapAnswersPath:
              '/tmp/context-packs/orders-estate/qmd/bootstrap/bootstrap-answers.json',
            discoveryDraftPath:
              '/tmp/context-packs/orders-estate/qmd/bootstrap/discovery-structure.json',
            manifestPath: '/tmp/context-packs/orders-estate/qmd/repo-sources.json',
            planPath: '/tmp/context-packs/orders-estate/qmd/bootstrap/seed-plan.json',
            repositoryCount: 2,
            focusTargetCount: 2,
            primaryWorkingRepoIds: ['orders-api'],
            primaryFocusAreaIds: [],
            seedStatus: 'success',
            warnings: [],
          },
        },
      }),
      listContextPacks: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.list',
          mode: 'read-only',
          message: 'Discovered 2 context pack(s) from approved local sources.',
          activeContextPackDir: '/tmp/context-packs/orders-estate',
          configuredPaths: [],
          searchRoots: [],
          recentContextPackDirs: ['/tmp/context-packs/orders-estate'],
          contextPacks: [
            {
              contextPackId: 'orders-estate',
              displayName: 'Orders Estate',
              contextPackDir: '/tmp/context-packs/orders-estate',
              manifestPath: '/tmp/context-packs/orders-estate/qmd/repo-sources.json',
              bootstrapReady: true,
              source: 'active-env',
              isActive: true,
              estateType: 'distributed-platform',
              defaultScopeMode: 'focused',
              repoCount: 2,
              primaryWorkingRepoIds: ['orders-api'],
              focusTargets: [
                {
                  focusId: 'orders-api',
                  displayName: 'Orders API',
                  kind: 'repository',
                  repoId: 'orders-api',
                  serviceName: 'Orders API',
                  systemLayer: 'backend',
                  repoRole: 'backend-service',
                  repositoryType: null,
                  relativePath: null,
                  focusType: null,
                  group: null,
                  defaultFocusable: true,
                  activationPriority: 10,
                  adjacentRepoIds: ['orders-web'],
                  adjacentFocusIds: [],
                },
                {
                  focusId: 'orders-web',
                  displayName: 'Orders Web',
                  kind: 'repository',
                  repoId: 'orders-web',
                  serviceName: 'Orders Web',
                  systemLayer: 'frontend',
                  repoRole: 'frontend',
                  repositoryType: null,
                  relativePath: null,
                  focusType: null,
                  group: null,
                  defaultFocusable: false,
                  activationPriority: 5,
                  adjacentRepoIds: ['orders-api'],
                  adjacentFocusIds: [],
                },
              ],
            },
            {
              contextPackId: 'billing-estate',
              displayName: 'Billing Estate',
              contextPackDir: '/tmp/context-packs/billing-estate',
              manifestPath: '/tmp/context-packs/billing-estate/qmd/repo-sources.json',
              bootstrapReady: true,
              source: 'search-root',
              isActive: false,
              estateType: 'distributed-platform',
              defaultScopeMode: 'focused',
              repoCount: 1,
              primaryWorkingRepoIds: ['billing-api'],
              focusTargets: [
                {
                  focusId: 'billing-api',
                  displayName: 'Billing API',
                  kind: 'repository',
                  repoId: 'billing-api',
                  serviceName: 'Billing API',
                  systemLayer: 'backend',
                  repoRole: 'backend-service',
                  repositoryType: null,
                  relativePath: null,
                  focusType: null,
                  group: null,
                  defaultFocusable: true,
                  activationPriority: 8,
                  adjacentRepoIds: [],
                  adjacentFocusIds: [],
                },
              ],
            },
          ],
        },
      }),
      listRepoTree: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.listRepoTree',
          mode: 'read-only',
          message: 'Listed repo tree entries.',
          entries: [],
          currentPath: '',
          repoLocalPath: '/tmp/context-packs/orders-estate/orders-api',
          truncated: false,
        },
      }),
      reseedContextPack: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.reseed',
          mode: 'reseeded',
          message:
            'Context-pack reseed completed through the approved repo-context seed seam. Conventions memo generation remains only-if-missing.',
          commandPath: 'src/backend/scripts/python/repo-context-app.py',
          result: {
            contextPackDir: '/tmp/context-packs/orders-estate',
            overallStatus: 'seeded',
            reportPath: '/tmp/report.json',
            seededRepoCount: 2,
            blockedRepoCount: 0,
            conventionsSummaryStatus: 'available',
            conventionsPolicy: 'only-if-missing',
          },
        },
      }),
      setRepositoryType: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'contextPack.setRepositoryType', mode: 'updated', message: 'Updated.' },
      }),
      previewContextPackSwitch: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.previewSwitch',
          mode: 'preview',
          message:
            'Context-pack workspace preview completed through the approved wrapper seam.',
          commandPath: 'src/backend/platform/context-pack/switch.ts',
          result: {
            ok: true,
            wrapperAction: 'preview',
            stage: 'complete',
            status: 'success',
            activation: {
              performed: false,
              exitCode: null,
              output: '',
            },
            envStateCleared: false,
            error: null,
            contextPackId: 'orders-estate',
            contextPackDir: '/tmp/context-packs/orders-estate',
            workspaceFile: '/repo/tasksail.code-workspace',
            stateFile: '/repo/.platform-state/workspace-context-sync.json',
            scopeMode: 'focused',
            selectedRepoIds: ['orders-api'],
            selectedFocusIds: [],
            warnings: ['orders-web is missing on disk'],
            foldersToAdd: ['/tmp/context-packs/orders-estate'],
            foldersToRemove: [],
            managedFolders: ['/tmp/context-packs/orders-estate'],
            targetFolders: ['/tmp/context-packs/orders-estate'],
            lastSyncedAt: null,
          },
        },
      }),
      applyContextPackSwitch: vi.fn().mockResolvedValue({
        ok: false,
        action: 'contextPack.applySwitch',
        error: 'Activation failed.',
        contextPackResult: {
          ok: false,
          wrapperAction: 'apply',
          stage: 'activation',
          status: 'error',
          activation: {
            performed: true,
            exitCode: 1,
            output: 'activation failed',
          },
          envStateCleared: false,
          error: 'Activation failed.',
          contextPackId: null,
          contextPackDir: '/tmp/context-packs/orders-estate',
          workspaceFile: null,
          stateFile: null,
          scopeMode: 'focused',
          selectedRepoIds: ['orders-api'],
          selectedFocusIds: [],
          warnings: [],
          foldersToAdd: [],
          foldersToRemove: [],
          managedFolders: [],
          targetFolders: [],
          lastSyncedAt: null,
        },
      }),
      clearActiveContextPack: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.clearActive',
          mode: 'cleared',
          message:
            'Active context-pack workspace state cleared through the approved wrapper seam.',
          commandPath: 'src/backend/platform/context-pack/switch.ts',
          result: {
            ok: true,
            wrapperAction: 'clear',
            stage: 'complete',
            status: 'cleared',
            activation: {
              performed: false,
              exitCode: null,
              output: '',
            },
            envStateCleared: true,
            error: null,
            contextPackId: null,
            contextPackDir: null,
            workspaceFile: '/repo/tasksail.code-workspace',
            stateFile: '/repo/.platform-state/workspace-context-sync.json',
            scopeMode: null,
            selectedRepoIds: [],
            warnings: [],
            foldersToAdd: [],
            foldersToRemove: ['/tmp/context-packs/orders-estate'],
            managedFolders: [],
            targetFolders: [],
            lastSyncedAt: '2026-03-08T11:00:00Z',
          },
        },
      }),
      submitPlannerDraft: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.submitDraft',
          mode: 'dry-run',
          accepted: true,
          message:
            'Planner draft accepted for local review only. No dropbox file or helper script was invoked.',
          draftTitle: 'x',
          suggestedPath: 'sequential',
        },
      }),
      initiateFollowUp: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'followup.begin',
          mode: 'dry-run',
          accepted: true,
          message:
            'Follow-up draft staged locally only. No child task has been created and the closed parent task remains unchanged.',
          suggestedTaskKind: 'child-task',
          sourceTaskId: 'CAP-CUSTOM-TERMINAL-04',
          parentTaskId: 'CAP-CUSTOM-TERMINAL-04',
          rootTaskId: 'CAP-CUSTOM-TERMINAL-01',
          reopenedTask: false,
        },
      }),
      activateContextPack: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'contextPack.activate',
          mode: 'dry-run',
          accepted: true,
          message:
            'Context-pack activation remains gated to the stable activation command and has not been executed.',
          commandPreview:
            'tsx src/backend/platform/context-pack/cli.ts --pack platform-default --mode status-only',
        },
      }),
      startPlannerSession: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.startSession',
          mode: 'started',
          accepted: true,
          message: 'Planner session started.',
          sessionId: 'planner-mock-1',
          brokerStatus: 'idle',
        },
      }),
      sendPlannerMessage: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.sendMessage',
          mode: 'sent',
          accepted: true,
          message: 'Message sent to planner session.',
        },
      }),
      endPlannerSession: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.endSession',
          mode: 'ended',
          accepted: true,
          message: 'Planner session ended.',
        },
      }),
      savePlannerDraft: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.saveDraft',
          mode: 'instructed',
          accepted: true,
          message: 'Save-draft instruction sent to planner session.',
          brokerStatus: 'completed',
        },
      }),
      readStagedDraft: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.readStagedDraft',
          mode: 'empty',
          message: 'No staged draft found in .staging/ directory.',
          draft: null,
          brokerStatus: 'completed',
        },
      }),
      finalizeSpec: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.finalizeSpec',
          mode: 'finalized',
          accepted: true,
          message: 'Spec promoted to dropbox.',
          destinationPath: '/repo/AgentWorkSpace/dropbox/20260318T120000Z-spec.md',
          brokerStatus: 'idle',
        },
      }),
      pickMarkdownFile: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.pickMarkdownFile',
          mode: 'cancelled',
          message: 'Markdown file selection was cancelled.',
          filename: null,
          path: null,
          content: null,
        },
      }),
      uploadSpec: vi.fn().mockResolvedValue({ ok: true, response: { action: 'planner.uploadSpec', mode: 'submitted', accepted: true, message: '', draftTitle: '', submittedPath: '', observationMode: true } }),
      listArchivedTasks: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'planner.listArchivedTasks',
          mode: 'empty',
          message: 'No archived tasks.',
          tasks: [],
        },
      }),
      submitReinforcementFeedback: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'reinforcement.submitFeedback',
          mode: 'submitted',
          passed: true,
          message: 'Reinforcement feedback submitted.',
        },
      }),
      updateRealignmentDoc: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'reinforcement.updateRealignmentDoc',
          mode: 'updated',
          passed: true,
          message: 'Global realignment document updated.',
        },
      }),
      readReinforcementOverview: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'reinforcement.readOverview' },
      }),
      listReinforcementTasks: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'reinforcement.listTasks', mode: 'read-only', message: '0 task(s).', tasks: [], availableYears: [] },
      }),
      readAgentRewards: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'reinforcement.readAgentRewards' },
      }),
      listRealignmentSessions: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'reinforcement.listRealignmentSessions' },
      }),
      readRealignmentDoc: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'reinforcement.readRealignmentDoc',
          mode: 'read-only',
          message: 'No document yet.',
          document: {
            standingExpectations: [],
            behavioralGuidance: [],
            lessonsLearned: [],
            fairnessFraming: [],
            version: 0,
            updatedAt: '',
          },
        },
      }),
      checkActiveWorkGuard: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'reinforcement.checkActiveWorkGuard',
          mode: 'guard-check',
          allowed: true,
          message: 'No active work. Corrective realignment is allowed.',
          activeTaskId: null,
        },
      }),
      startRealignment: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'reinforcement.startRealignment',
          mode: 'started',
          message: 'Corrective realignment session started.',
          session: {
            realignmentId: 'RA-mock',
            triggerTaskId: 'T-1',
            triggerFeedbackId: 'ui-triggered',
            participatingAgents: [],
            failureAnalysis: '',
            rootCause: '',
            correctiveActions: [],
            status: 'open',
            meetingNotes: '',
            createdAt: '2026-03-23T00:00:00Z',
          },
        },
      }),
      listExternalMcpServers: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'externalMcp.list', mode: 'read-only', message: '0 server(s) configured.', servers: [] },
      }),
      addExternalMcpServer: vi.fn().mockResolvedValue({ ok: true, response: { action: 'externalMcp.add', mode: 'mutated', message: 'Added.', servers: [] } }),
      updateExternalMcpServer: vi.fn().mockResolvedValue({ ok: true, response: { action: 'externalMcp.update', mode: 'mutated', message: 'Updated.', servers: [] } }),
      removeExternalMcpServer: vi.fn().mockResolvedValue({ ok: true, response: { action: 'externalMcp.remove', mode: 'mutated', message: 'Removed.', servers: [] } }),
      toggleExternalMcpServer: vi.fn().mockResolvedValue({ ok: true, response: { action: 'externalMcp.toggleEnabled', mode: 'mutated', message: 'Toggled.', servers: [] } }),
      validateExternalMcpConnection: vi.fn().mockResolvedValue({ ok: true, response: { action: 'externalMcp.validateConnection', mode: 'validated', success: true, message: 'OK.' } }),
      loadAgentConfig: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'agentConfig.loadAgents',
          mode: 'read-only',
          message: 'Loaded 4 agent assignments.',
          agents: [
            {
              agent_id: 'planning-agent',
              human_name: 'Lily',
              role_name: 'Planning Specialist',
              required_model: 'gpt-4.1',
              workflow_order: 0,
            },
            {
              agent_id: 'product-manager',
              human_name: 'Alice',
              role_name: 'Product Manager',
              required_model: 'gpt-5.4',
              workflow_order: 1,
            },
            {
              agent_id: 'software-engineer',
              human_name: 'Dalton',
              role_name: 'Software Engineer',
              required_model: 'claude-sonnet-4.6',
              workflow_order: 2,
            },
            {
              agent_id: 'qa',
              human_name: 'Ron',
              role_name: 'QA and Closeout',
              required_model: 'gpt-5.4',
              workflow_order: 3,
            },
          ],
        },
      }),
      loadModelCatalog: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'agentConfig.loadModelCatalog',
          mode: 'read-only',
          message: 'Loaded 3 model(s).',
          models: [
            { display_name: 'GPT 4.1', model_id: 'gpt-4.1' },
            { display_name: 'GPT 5.4', model_id: 'gpt-5.4' },
            { display_name: 'Claude Sonnet 4.6', model_id: 'claude-sonnet-4.6' },
          ],
        },
      }),
      saveAgentModels: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'agentConfig.saveAgentModels',
          mode: 'mutated',
          message: 'Agent assignments saved.',
          agents: [
            {
              agent_id: 'planning-agent',
              human_name: 'Lily',
              role_name: 'Planning Specialist',
              required_model: 'gpt-4.1',
              workflow_order: 0,
            },
            {
              agent_id: 'product-manager',
              human_name: 'Alice',
              role_name: 'Product Manager',
              required_model: 'gpt-5.4',
              workflow_order: 1,
            },
            {
              agent_id: 'software-engineer',
              human_name: 'Dalton',
              role_name: 'Software Engineer',
              required_model: 'claude-sonnet-4.6',
              workflow_order: 2,
            },
            {
              agent_id: 'qa',
              human_name: 'Ron',
              role_name: 'QA and Closeout',
              required_model: 'gpt-5.4',
              workflow_order: 3,
            },
          ],
        },
      }),
      addModel: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'agentConfig.addModel',
          mode: 'mutated',
          message: 'Model added.',
          models: [
            { display_name: 'GPT 4.1', model_id: 'gpt-4.1' },
            { display_name: 'GPT 5.4', model_id: 'gpt-5.4' },
            { display_name: 'Claude Sonnet 4.6', model_id: 'claude-sonnet-4.6' },
            { display_name: 'GPT 5.5', model_id: 'gpt-5.5' },
          ],
        },
      }),
      removeModel: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'agentConfig.removeModel',
          mode: 'mutated',
          message: 'Model removed.',
          models: [
            { display_name: 'GPT 4.1', model_id: 'gpt-4.1' },
            { display_name: 'GPT 5.4', model_id: 'gpt-5.4' },
          ],
        },
      }),
      readTaskBoard: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'taskBoard.readBoard',
          mode: 'read-only',
          message: '0 open, 0 pending, 0 failed, 0 completed.',
          dropboxItems: [],
          pendingItems: [],
          errorItems: [],
          completedItems: [],
        },
      }),
      readTaskContent: vi.fn().mockResolvedValue({
        ok: true,
        response: {
          action: 'taskBoard.readTaskContent',
          mode: 'not-found',
          message: 'Not found.',
          content: '',
          fileName: '',
        },
      }),
      reorderPending: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'taskBoard.reorderPending', mode: 'reordered', message: 'Reordered.' },
      }),
      requeueErrorItem: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'taskBoard.requeueErrorItem', mode: 'requeued', message: 'Requeued.', requeuedItem: 'task.md' },
      }),
      deleteTask: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'taskBoard.deleteTask', mode: 'deleted', message: 'Deleted.', fileName: 'task.md', column: 'open' },
      }),
      moveToPending: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'taskBoard.moveToPending', mode: 'moved', message: 'Moved.', movedItem: 'task.md' },
      }),
      moveToOpen: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'taskBoard.moveToOpen', mode: 'moved', message: 'Moved.', movedItem: 'task.md' },
      }),
      getBackendServiceStatus: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'services.readStatus', mode: 'observed', status: 'idle', lastCheckedAt: null, error: null, message: 'Backend services not started.' },
      }),
      startBackendServices: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'services.readStatus', mode: 'observed', status: 'healthy', lastCheckedAt: null, error: null, message: 'Backend services are running.' },
      }),
      stopBackendServices: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'services.readStatus', mode: 'observed', status: 'idle', lastCheckedAt: null, error: null, message: 'Backend services not started.' },
      }),
      checkBackendHealth: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'services.readStatus', mode: 'observed', status: 'healthy', lastCheckedAt: null, error: null, message: 'Backend services are running.' },
      }),
      listInstructionFiles: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'agentInstructions.listFiles', mode: 'read-only', message: '0 file(s).', files: [] },
      }),
      readInstructionFile: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'agentInstructions.readFile', mode: 'read-only', message: 'Read.', fileName: '', relativePath: '', content: '' },
      }),
      writeInstructionFile: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'agentInstructions.writeFile', mode: 'mutated', message: 'Saved.', fileName: '', relativePath: '' },
      }),
      saveDeepFocusSelections: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'deepFocus.saveSelections', mode: 'saved', message: 'Saved.' },
      }),
      loadDeepFocusSelections: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'deepFocus.loadSelections', mode: 'read-only', message: 'No saved selections found.', selections: null },
      }),
      clearDeepFocusSelections: vi.fn().mockResolvedValue({
        ok: true,
        response: { action: 'deepFocus.clearSelections', mode: 'cleared', message: 'Cleared.' },
      }),
    } as typeof window.desktopShell & Record<string, unknown>;
  });
}
